version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
    restart: always
    volumes: 
      - ./backend:/app
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    environment:
      WATCHPACK_POLLING: true
    volumes:
      - ./frontend:/app
      - /app/node_modules  # ホスト側のnode_modulesを使わないようにする
